<?php

/**
 * @file
 * The xmas top 100 module!
 */

/**
 * Implements hook_perm().
 */
function xmas_perm() {
  return array('administer xmas');
}
/**
 * Implements hook_node_info().
 */
function xmas_node_info() {
  return array(
    'song' => array(
      'name' => t('Song'),
      'module' => 'xmas',
      'description' => t("A song, normally added by the xmas module."),
	  'has_body' => FALSE,
    )
  );
}


/**
 * Implements hook_menu().
 */
function xmas_menu() {
  $items = array();

  $items['admin/content/xmas'] = array(
    'title' => 'XMas', 
    'description' => 'Update the xmas listing and set the xmas settings.', 
    'page callback' => 'drupal_get_form',
    'page arguments' => array('xmas_admin'),  
    'access arguments' => array('administer xmas'), 
  );

  return $items;
}

/**
 * Menu Callback; the xmas admin settings.
 */
function xmas_admin() {
  $form = array();
  
  
  return $form;
}


/**
 * Form Callback; The validation of the admin settings form.
 */
function xmas_admin_validate() {}
 
/**
 * Form Callback; The submit hook of the admin settings form.
 */
 function xmas_admin_submit() {}